# Tyler Sabin
# sabint@live.com
# 6/9/2024
# CNE 370 Spring Quarter 2024
# This code configures for a CI pipeline
# source https://github.com/mariadb-corporation/MaxScale/blob/2.3/Documentation/Tutorials/Simple-Sharding-Tutorial.md
# source https://github.com/mariadb-corporation/MaxScale/blob/2.3/Documentation/Documentation-Contents.md
# source https://github.com/mariadb-corporation/MaxScale/blob/2.3/Documentation/Getting-Started/Configuration-Guide.md
# source https://github.com/mariadb-corporation/MaxScale/blob/2.3/Documentation/Reference/MaxAdmin.md
# source https://mariadb.com/kb/en/mariadb-maxscale-25-simple-sharding-with-two-servers/
# source https://github.com/Zohan/maxscale-docker
# source Brian Huang
# code modified by Tyler Sabin

language: bash
services: docker
env:
  - VERSION=maxscale

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/mariadb-docker-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="maxscale-docker:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/mariadb-docker-images/test/run.sh "$image"

after_script:
- docker images

notifications:
  email:
    recipients:
      - cpe@mariadb.com
    on_success: never # default: change
    on_failure: always # default: always
